name:                launchdarkly-server-sdk-redis-hedis
version:             0.1.0
github:              "launchdarkly/haskell-server-sdk-redis-hedis"
license:             Apache-2.0
license-file:        "LICENSE"
author:              "LaunchDarkly"
maintainer:          "dev@launchdarkly.com"
copyright:           "2023 Catamorphic, Co"

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE

synopsis:            LaunchDarkly Server-Side SDK - Redis Integration
category:            Web

description:         Please see the README on GitHub at <https://github.com/launchdarkly/haskell-server-sdk-redis-hedis#readme>
library:
  source-dirs: src
  exposed-modules:
    - LaunchDarkly.Server.Store.Redis
  ghc-options:
  - -fwarn-unused-imports
  - -Wall
  - -Wno-name-shadowing

dependencies:
  - aeson >=1.4.4.0 && <1.6 || >= 2.0.1.0 && <2.2
  - base >=4.7 && <5
  - bytestring >=0.10.8.2 && <0.12
  - exceptions >=0.10.2 && <0.11
  - hedis >=0.12.7 && <0.16
  - generic-lens >=1.1.0.0 && <2.3
  - text >=1.2.3.1 && <2.1
tests:
  haskell-server-sdk-redis-hedis-test:
    main: Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-name-shadowing
    - -fwarn-unused-imports
    - -Wall
    dependencies:
    - HUnit

default-extensions:
- DataKinds
- DeriveAnyClass
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
