version: 2.1

jobs:
  build-test-linux:
    resource_class: medium+
    parameters:
        resolver:
            type: string
    docker:
        - image: haskell:latest
        - image: redis
    steps:
      - checkout
      - run:
          name: Install libpcre
          command: pkg-config --exists libpcre || apt-get update && apt-get install -y --no-install-recommends libpcre3-dev
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v1-linux-<<parameters.resolver>>-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal --resolver=<<parameters.resolver>> setup --install-ghc
      - run:
          name: Build library
          command: stack --no-terminal --resolver=<<parameters.resolver>> build
      - run:
          name: Run tests
          command: stack --no-terminal --resolver=<<parameters.resolver>> test
      - save_cache:
          name: Cache Dependencies
          key: haskell-v1-linux-<<parameters.resolver>>-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  build-test-osx:
    parameters:
        resolver:
            type: string
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Install deps
          command: brew install haskell-stack pcre pkg-config redis
      - run:
          name: Redis
          command: redis-server
          background: true
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v3-osx-<<parameters.resolver>>-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal --resolver=<<parameters.resolver>> setup --install-ghc
      - run:
          name: Build
          command: stack --no-terminal --resolver=<<parameters.resolver>> build
      - run:
          name: Run tests
          command: stack --no-terminal --resolver=<<parameters.resolver>> test
      - save_cache:
          name: Cache Dependencies
          key: haskell-v3-osx-<<parameters.resolver>>-{{ checksum "package.yaml" }}
          paths:
            - "/Users/distiller/.stack"
            - ".stack-work"

  run-quality-checks:
    docker:
      - image: haskell:9.0.2
    working_directory: ~/sdk
    steps:
      - checkout
      - run:
          name: install dependencies
          command: apt-get update && apt-get install -y --no-install-recommends jq git
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - quality-checks-v0
      - run:
          name: install hpack and fourmolu
          command: |
            cd ..
            cabal update
            cabal install hpack-0.35.1 --overwrite-policy=always
            cabal install fourmolu-0.10.1.0 --overwrite-policy=always
            cd -
      - run:
          name: verify the generated .cabal file is up-to-date
          command: |
            hpack
            if [ $(git status --porcelain | wc -l) -gt 0 ]; then
              echo "hpack resulted in modified files. please run hpack locally and commit those changes"
              echo ""
              echo "showing the results of `git status`"
              git status
              exit -1
            fi
      - run:
          name: install and run hlint
          command:
            curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
      - run:
          name: run formatting check
          command: fourmolu --mode check src test
      - save_cache:
          name: Cache Dependencies
          key: quality-checks-v0
          paths:
            - "/root/.cabal"

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - run-quality-checks
      - build-test-linux:
          matrix:
              parameters:
                resolver: ["lts-16.31", "lts-18.28", "lts-19.33", "lts-20.11"]
      - build-test-osx:
          matrix:
              parameters:
                resolver: ["lts-16.31", "lts-18.28", "lts-19.33", "lts-20.11"]
